# Generated by Django 4.2.6 on 2023-10-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coures", "0003_tag_alter_course_category_alter_course_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="descrption", new_name="description",
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
