# Generated by Django 4.2.6 on 2023-10-29 07:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coures", "0004_rename_descrption_course_description_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="lesson", name="context", field=ckeditor.fields.RichTextField(),
        ),
    ]
