# Generated by Django 4.2.6 on 2023-10-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coures", "0005_alter_course_description_alter_lesson_context"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="description", new_name="descrption",
        ),
    ]
